# Generated by Django 3.2.18 on 2023-05-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230517_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='excerpt',
        ),
    ]
